# Generated by Django 5.0.3 on 2024-04-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
    ]
